# Dockerfile for FastAPI
FROM python:3.10


COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Встановлюємо FastAPI та uvicorn
RUN pip install fastapi uvicorn

# Копіюємо код додатку
COPY . /app
WORKDIR /app

# Відкриваємо порт для FastAPI
EXPOSE 8000

# Запуск FastAPI через uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
