version: "3.8"

services:
  ib_gateway:
    build:
      context: .
      dockerfile: Dockerfile.ib_gateway  # Вказуємо конкретний Dockerfile для IB Gateway
    container_name: ib_gateway
    environment:
      - TWS_USER=${TWS_USER}
      - TWS_PASSWORD=${TWS_PASSWORD}
      - IBC_TRADING_MODE=${IBC_TRADING_MODE}
      - IBC_MODE=${IBC_MODE}
      - TWS_PORT=${TWS_PORT}
      - IB_HOST=${IB_HOST}
      - IB_CLIENT_ID=${IB_CLIENT_ID}
    ports:
      - "7497:7497"  # Порт IB Gateway
    volumes:
      - ./data:/data
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Вказуємо конкретний Dockerfile для FastAPI
    container_name: fastapi
    ports:
      - "8029:8000"
    depends_on:
      - ib_gateway
    restart: always
