version: "3.8"

services:
  ib_gateway:
    build: .
    container_name: ib_gateway
    environment:
      - TWS_USER=${TWS_USER}
      - TWS_PASSWORD=${TWS_PASSWORD}
      - IBC_TRADING_MODE=${IBC_TRADING_MODE}
      - IBC_MODE=${IBC_MODE}
      - TWS_PORT=${TWS_PORT}
      - IB_HOST=${IB_HOST}
      - IB_CLIENT_ID=${IB_CLIENT_ID}
    ports:
      - "8021:8000"  # FastAPI
      - "7497:7497"  # Порт IB Gateway
    volumes:
      - ./data:/data
    restart: always

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8022:8000"
    depends_on:
      - ib_gateway
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
