Vagrant.configure("2") do |config|
  # Налаштування для віртуальної машини DB_VM
  config.vm.define "dbvm" do |dbvm|
    # Вказуємо базовий образ для віртуальної машини
    dbvm.vm.box = "ubuntu/bionic64"
    
    # Налаштовуємо приватну мережу з IP адресою для DB_VM
    dbvm.vm.network "private_network", ip: "192.168.56.10"
    
    # Встановлюємо hostname для DB_VM
    dbvm.vm.hostname = "dbvm"
    
    # Налаштовуємо провізінг для DB_VM за допомогою shell скрипту
    # Скрипт db_provision.sh буде виконано для налаштування бази даних
    dbvm.vm.provision "shell", path: "db_provision.sh"
  end

  # Налаштування для віртуальної машини APP_VM
  config.vm.define "appvm" do |appvm|
    # Вказуємо базовий образ для віртуальної машини
    appvm.vm.box = "ubuntu/bionic64"
    
    # Налаштовуємо приватну мережу з IP адресою для APP_VM
    appvm.vm.network "private_network", ip: "192.168.56.11"
    
    # Налаштовуємо публічну мережу
    appvm.vm.network "public_network", bridge: "Realtek RTL8821CE 802.11ac PCIe Adapter"
    
    # Встановлюємо hostname для APP_VM
    appvm.vm.hostname = "appvm"
    
    # Налаштовуємо переадресацію портів для APP_VM
    # Порт 8080 на віртуальній машині буде доступний на порту 8088 на хості
    appvm.vm.network "forwarded_port", guest: 8080, host: 8088
    
    # Налаштовуємо провізінг для APP_VM за допомогою shell скрипту
    # Скрипт app_provision.sh буде виконано для налаштування додатку
    appvm.vm.provision "shell", path: "app_provision.sh"
  end
end



# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
#Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
 # config.vm.box = "ubuntu/jammy64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
#end
