apiVersion: v1
kind: Service
metadata:
  name: python-random-service
spec:
  selector:
    app: python-random
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer
