global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.112.128:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.112.128:9100']  

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.112.128:8080']

  - job_name: 'docker_exporter'
    static_configs:
      - targets: ['docker_exporter:9323']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['192.168.112.128:9093']

rule_files:
  - "/etc/prometheus/alert.rules"  

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.112.128:9093']  
