---
- name: Configure EC2 instances
  hosts: all
  become: yes
  tasks:

    # Оновлення та оновлення пакетів
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: yes
        cache_valid_time: 3600
      become: yes

    # Встановлення необхідних пакетів для Docker
    - name: Install required packages for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      become: yes

    # Завантаження Docker GPG ключа через apt_key
    - name: Add Docker's GPG key to keyring
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    # Додавання Docker репозиторію
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present
      become: yes

    # Встановлення Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      become: yes

    # Встановлення Docker Compose
    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      become: yes

    # Перевірка версії Docker Compose
    - name: Check Docker Compose version
      command: /usr/local/bin/docker-compose --version
      become: yes

    # Пулінг образу Nginx
    - name: Pull Nginx Docker image
      docker_image:
        name: nginx
        source: pull
      become: yes

    # Створення файлу docker-compose.yml
    - name: Create docker-compose.yml file
      copy:
        content: |
          version: '3'
          services:
            nginx:
              image: nginx
              ports:
                - "80:80"
        dest: /home/ubuntu/docker-compose.yml
      become: yes

    # Запуск Nginx через Docker Compose
    - name: Run Nginx with Docker Compose
      command: docker-compose -f /home/ubuntu/docker-compose.yml up -d
      become: yes
