version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: homework13-app

  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    container_name: homework13-nginx
