Vagrant.configure("2") do |config|

  # # Jenkins Master Node
  config.vm.define "jenkins-master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.network "private_network", type: "dhcp"
    master.vm.network "public_network", bridge: "Realtek RTL8821CE 802.11ac PCIe Adapter"
    master.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openjdk-11-jre
      wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /etc/apt/trusted.gpg.d/jenkins.asc
      sudo sh -c 'echo deb http://pkg.jenkins.io/debian/jenkins.io/ stable main > /etc/apt/sources.list.d/jenkins.list'
      sudo apt-get update
      sudo apt-get install -y jenkins
      sudo systemctl start jenkins
      sudo systemctl enable jenkins
    SHELL
  end

  # Налаштування для jenkins-worker
  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "ubuntu/bionic64"
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.network "public_network", bridge: "Realtek RTL8821CE 802.11ac PCIe Adapter"
    worker.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y docker.io docker-compose
      sudo systemctl enable docker
      sudo systemctl start docker
      sudo usermod -aG docker vagrant
    SHELL
  end
end
